Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeOut: 60
  WriteTimeOut: 60

Database:
  DBType: mysql
  Username: root
  Password: 212134
  Host: 127.0.0.1:3306
  DBName: ee_album
  TablePrefix:
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30