Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeOut: 60
  WriteTimeOut: 60

Database:
  DBType: mysql # [mysql, sqlite]
  Username:
  Password:
  Host: 127.0.0.1:3306
  DBName: 
  TablePrefix:
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

  RedisAddr: 127.0.0.1:6379
  RedisPassword:
  RedisDB: 0

Jwt:
  Key:

Storage:
  GalleryCoverPath:
  PicturePath:
  AvatarPath:

# 阿里云OSS对象存储
OSS:
  END_POINT:
  ACCESS_KEY_ID:
  ACCESS_KEY_SECRET:
  BUCKET: