Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeOut: 60
  WriteTimeOut: 60

Database:
  DBType: mysql
  Username:
  Password:
  Host: 127.0.0.1:3306
  DBName: 
  TablePrefix:
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

  Jwt:
    Key:

  Storage:
    GalleryCoverPath:
    PicturePath:
    AvatarPath:

  OSS:
    END_POINT:
    ACCESS_KEY_ID:
    ACCESS_KEY_SECRET:
    BUCKET: